### ISSUE TITLE
Add pull request template

### ISSUE THREAD

**Issue by meshy** [meshy/django-conman#104]
As per [github's instructions](https://github.com/blog/2111-issue-and-pull-request-templates).

Shouldn't be huge, just a quick checklist:

- tests / styles (flake8 etc)
- change log
- docs

Am I missing anything?

**Comment by Amrithasuresh** [comment]
@meshy I will do this.
1) I have to create a single file "PULL_REQUEST_TEMPLATE.md".
2) Add the above-mentioned checklist.

Am I right? Thank you.

**Comment by meshy** [comment]
Thank you very much! That's everything I can think of -- if I think of anything else, that can be added later.

I had no idea that anyone had even noticed this project! Your help is much appreciated.

**Comment by Amrithasuresh** [comment]
>I had no idea that anyone had even noticed this project! Your help is much appreciated.

@meshy I was looking for "low hanging fruit" tag, and then I came to know about this. Happy to contribute and learn.

Can you please check this [file](https://github.com/Amrithasuresh/django-conman/blob/master/PULL_REQUEST_TEMPLATE.md)? Do I need to explain? Later, I can give a PR. Thank you.

**Comment by meshy** [comment]
Now that I have a look at it, I realise that my list isn't entirely helpful. I hope you don't mind the update -- I would indeed like a PR, but perhaps something like this would be more approachable for contributors:

---


```markdown
**Please fill in the following help with this PR:**

_What was the problem:_

_How this solves the problem:_

_Please ensure you have (if appropriate):_

- [ ] Run the test suite / style guide checkers.
- [ ] Added tests.
- [ ] Updated the docs.
- [ ] Updated the changelog.
```

---

> I was looking for "low hanging fruit" tag, and then I came to know about this.

Aah! That makes sense! Glad I added them now `;)` Thanks again for your assistance.

**Comment by Amrithasuresh** [comment]
@meshy I have updated the file. Have a look at the [file](https://github.com/Amrithasuresh/django-conman/blob/master/PULL_REQUEST_TEMPLATE.md). Thank you.

**Comment by meshy** [comment]
Thank you! Please open a PR, and I will merge it!
