### ISSUE TITLE
Set up package signing with twine

### ISSUE THREAD

**Issue by meshy** [meshy/django-conman#105]
https://pypi.python.org/pypi/twine

**Comment by Amrithasuresh** [comment]
@meshy Can you please explain what exactly one should do here.

**Comment by meshy** [comment]
I'm afraid that this might be a task for me, as it'll involve signing the packages that go to PyPI with GPG keys.

I've removed the tag to avoid confusion.

**Comment by meshy** [comment]
Done in 610d76c2496c29bccff3126548dce51f78c7bc9a and 3265b8d2d02f8cac1e82e095e7c3ceecb4caacf4.
