### ISSUE TITLE
Split into apps

### ISSUE THREAD

**Issue by meshy** [meshy/django-conman#51]
~~- [ ] Move `conman.pages` into `django-conman-sir-trevor` or `django-conman-pages`.~~ pages app has been removed entirely.
- [ ] Move `conman.redirects` into `django-conman-redirects` repo.
- [ ] Move `conman.routes` module up a level into `conman`.

**Comment by meshy** [comment]
I am in two minds as to whether I should keep `conman.routes` in `routes`, and might well change my mind on that before actually implementing this.

> Namespaces are one honking great idea -- let's do more of those!

**Comment by Ian-Foote** [comment]
I think `flat is better than nested` applies better here. :wink:

**Comment by meshy** [comment]
Yeah, may well be.

**Comment by meshy** [comment]
Closing, as not sure this is really required any more. I think the redirects are pretty universal, and the pages app is now gone.
