### ISSUE TITLE
Clean up structure of conman.routes.handlers

### ISSUE THREAD

**Issue by meshy** [meshy/django-conman#53]
it seems a little confusing.

**Comment by Ian-Foote** [comment]
Currently we have in `routes/handlers`:

* `__init__.py` - `base.BaseHandler` and `simple.SimpleHandler`
* `base`
 * `__init__.py` - `BaseHandler`
* `simple`
 * `__init__.py` - `SimpleHandler`
 * `urls.py`
 * `views.py` - `simple_route_view`

I think this would be a clear improvement:

* `routes/handlers.py` - `BaseHandler` and `SimpleHandler`
* `routes/simple`
 * `urls.py`
 * `views.py` - `simple_route_view`

**Comment by meshy** [comment]
Much better :)
