### ISSUE TITLE
Render a page properly in page_detail.html

### ISSUE THREAD

**Issue by Ian-Foote** [meshy/django-conman#65]
Currently viewing a `Page` just displays its `json` representation.

**Comment by meshy** [comment]
[The template](https://github.com/meshy/django-conman/blob/5b78b3f4550276c7fe2a9bb9bf46608fc0d408b5/conman/pages/templates/pages/page_detail.html#L1) could be updated to render the content correctly:

```
{{ page.content.html|safe }}
```

But that would mean marking the content as safe by default, and I don't think I trust that. One solution would be to use `django-bleach` instead, but that will be useless if (for whatever reason) one needed to output a script tag from one of the content blocks. Perhaps we could improve `django-sirtrevor`, or perhaps we will need to go in another direction.

**Comment by meshy** [comment]
For reference, my new (as yet non-function) attempt to use Sir Trevor sensibly.

https://github.com/meshy/django-sirtrevor-field

**Comment by meshy** [comment]
As the pages module is gone (for the moment, at least), I'm closing this issue.
